/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Restuarant_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author koladeadegbaye
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setSize(800,600);
        setLocation(300,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        food_inventory_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        show_menu_btn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        make_order_btn = new javax.swing.JButton();
        show_orders_btn = new javax.swing.JButton();
        show_inventory_btn = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        addItemPanel = new javax.swing.JPanel();
        addMenuID1 = new javax.swing.JTextField();
        addPrice1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addItemName1 = new javax.swing.JTextField();
        addingTitlePanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        addItemBtn1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        addCategory1 = new javax.swing.JTextField();
        menuTabs = new javax.swing.JTabbedPane();
        menuPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable1 = new javax.swing.JTable();
        add_item_btn = new javax.swing.JButton();
        edit_item_btn = new javax.swing.JButton();
        delete_item_btn = new javax.swing.JButton();
        menuPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuTable2 = new javax.swing.JTable();
        menuPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        menuTable3 = new javax.swing.JTable();
        menuPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        menuTable4 = new javax.swing.JTable();
        menuPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        menuTable5 = new javax.swing.JTable();
        editItemPanel = new javax.swing.JPanel();
        editMenuID = new javax.swing.JTextField();
        editPrice = new javax.swing.JTextField();
        editMenuLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editCategory = new javax.swing.JTextField();
        editItemName = new javax.swing.JTextField();
        editingTitlePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        showInventoryPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        addingTitlePanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        showInventoryTable = new javax.swing.JTable();
        rmsTitlePanel = new javax.swing.JPanel();
        rmsTitleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rightIcon = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Food Inventory");

        javax.swing.GroupLayout food_inventory_panelLayout = new javax.swing.GroupLayout(food_inventory_panel);
        food_inventory_panel.setLayout(food_inventory_panelLayout);
        food_inventory_panelLayout.setHorizontalGroup(
            food_inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(food_inventory_panelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        food_inventory_panelLayout.setVerticalGroup(
            food_inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(food_inventory_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(571, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(94, 158, 145));
        jLabel1.setFont(new java.awt.Font("Al Nile", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESTAURANT MANAGEMENT SYSTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.lightGray, null, null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(842, 601));
        setSize(new java.awt.Dimension(842, 601));

        jPanel1.setBackground(new java.awt.Color(0, 78, 34));
        jPanel1.setMinimumSize(new java.awt.Dimension(208, 500));

        show_menu_btn.setBackground(new java.awt.Color(255, 255, 255));
        show_menu_btn.setForeground(new java.awt.Color(0, 102, 0));
        show_menu_btn.setText("Show menu");
        show_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_menu_btnActionPerformed(evt);
            }
        });

        logoutBtn.setForeground(new java.awt.Color(0, 102, 0));
        logoutBtn.setText("Logout");
        logoutBtn.setPreferredSize(new java.awt.Dimension(50, 29));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        make_order_btn.setForeground(new java.awt.Color(0, 102, 0));
        make_order_btn.setText("Make order");
        make_order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_order_btnActionPerformed(evt);
            }
        });

        show_orders_btn.setForeground(new java.awt.Color(0, 102, 0));
        show_orders_btn.setText("Show orders");
        show_orders_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_orders_btnActionPerformed(evt);
            }
        });

        show_inventory_btn.setForeground(new java.awt.Color(0, 102, 0));
        show_inventory_btn.setText("Show inventory");
        show_inventory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_inventory_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(show_inventory_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_menu_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(make_order_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_orders_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(show_menu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(make_order_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(show_orders_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(show_inventory_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        displayPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        displayPanel.setMinimumSize(new java.awt.Dimension(450, 400));
        displayPanel.setPreferredSize(new java.awt.Dimension(601, 501));
        displayPanel.setSize(new java.awt.Dimension(600, 500));
        displayPanel.setLayout(new java.awt.CardLayout());

        addItemPanel.setBackground(new java.awt.Color(255, 255, 255));
        addItemPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        addItemPanel.setMinimumSize(new java.awt.Dimension(450, 400));
        addItemPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        addItemPanel.setSize(new java.awt.Dimension(600, 500));

        addMenuID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuID1ActionPerformed(evt);
            }
        });

        addPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrice1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Menu ID:");

        jLabel12.setText("Price:");

        jLabel13.setText("Item_name:");

        addItemName1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        addItemName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemName1ActionPerformed(evt);
            }
        });

        addingTitlePanel1.setBackground(new java.awt.Color(255, 255, 255));
        addingTitlePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 78, 34), 2));

        jLabel15.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 78, 34));
        jLabel15.setText("Adding an Item");

        javax.swing.GroupLayout addingTitlePanel1Layout = new javax.swing.GroupLayout(addingTitlePanel1);
        addingTitlePanel1.setLayout(addingTitlePanel1Layout);
        addingTitlePanel1Layout.setHorizontalGroup(
            addingTitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addingTitlePanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        addingTitlePanel1Layout.setVerticalGroup(
            addingTitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addingTitlePanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(17, 17, 17))
        );

        addItemBtn1.setText("Add New Item");
        addItemBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtn1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Category");

        addCategory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategory1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addItemPanelLayout = new javax.swing.GroupLayout(addItemPanel);
        addItemPanel.setLayout(addItemPanelLayout);
        addItemPanelLayout.setHorizontalGroup(
            addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPanelLayout.createSequentialGroup()
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addingTitlePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addItemPanelLayout.createSequentialGroup()
                        .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addItemPanelLayout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(addItemPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(41, 41, 41)
                                        .addComponent(addMenuID1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addItemPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(24, 24, 24)
                                        .addComponent(addItemName1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addItemPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addItemPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(addItemPanelLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(addItemPanelLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(addItemBtn1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addItemPanelLayout.setVerticalGroup(
            addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addingTitlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMenuID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(addItemName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addItemBtn1)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        displayPanel.add(addItemPanel, "card4");

        menuTabs.setPreferredSize(new java.awt.Dimension(600, 500));
        menuTabs.setSize(new java.awt.Dimension(600, 500));
        menuTabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTabsMouseClicked(evt);
            }
        });

        menuPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPanel1MouseClicked(evt);
            }
        });

        menuTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu_ID:", "Item_name:", "Price:", "Category:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menuTable1);
        if (menuTable1.getColumnModel().getColumnCount() > 0) {
            menuTable1.getColumnModel().getColumn(0).setResizable(false);
            menuTable1.getColumnModel().getColumn(1).setResizable(false);
            menuTable1.getColumnModel().getColumn(2).setResizable(false);
            menuTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        add_item_btn.setForeground(new java.awt.Color(0, 102, 0));
        add_item_btn.setText("Add item");
        add_item_btn.setPreferredSize(new java.awt.Dimension(100, 29));
        add_item_btn.setSize(new java.awt.Dimension(100, 29));
        add_item_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_item_btnActionPerformed(evt);
            }
        });

        edit_item_btn.setForeground(new java.awt.Color(0, 102, 0));
        edit_item_btn.setText("Edit item");
        edit_item_btn.setSize(new java.awt.Dimension(100, 29));
        edit_item_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_item_btnActionPerformed(evt);
            }
        });

        delete_item_btn.setForeground(new java.awt.Color(0, 102, 0));
        delete_item_btn.setText("Delete item");
        delete_item_btn.setPreferredSize(new java.awt.Dimension(100, 29));
        delete_item_btn.setSize(new java.awt.Dimension(100, 9));
        delete_item_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_item_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanel1Layout = new javax.swing.GroupLayout(menuPanel1);
        menuPanel1.setLayout(menuPanel1Layout);
        menuPanel1Layout.setHorizontalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(add_item_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(edit_item_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(delete_item_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        menuPanel1Layout.setVerticalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_item_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_item_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuTabs.addTab("Full Menu", menuPanel1);

        menuPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPanel2MouseClicked(evt);
            }
        });

        menuTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu_ID:", "Item_name:", "Price:", "Category:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(menuTable2);
        if (menuTable2.getColumnModel().getColumnCount() > 0) {
            menuTable2.getColumnModel().getColumn(0).setResizable(false);
            menuTable2.getColumnModel().getColumn(1).setResizable(false);
            menuTable2.getColumnModel().getColumn(2).setResizable(false);
            menuTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout menuPanel2Layout = new javax.swing.GroupLayout(menuPanel2);
        menuPanel2.setLayout(menuPanel2Layout);
        menuPanel2Layout.setHorizontalGroup(
            menuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuPanel2Layout.setVerticalGroup(
            menuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        menuTabs.addTab("Appetizer", menuPanel2);

        menuPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPanel3MouseClicked(evt);
            }
        });

        menuTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu_ID:", "Item_name:", "Price:", "Category:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(menuTable3);
        if (menuTable3.getColumnModel().getColumnCount() > 0) {
            menuTable3.getColumnModel().getColumn(0).setResizable(false);
            menuTable3.getColumnModel().getColumn(1).setResizable(false);
            menuTable3.getColumnModel().getColumn(2).setResizable(false);
            menuTable3.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout menuPanel3Layout = new javax.swing.GroupLayout(menuPanel3);
        menuPanel3.setLayout(menuPanel3Layout);
        menuPanel3Layout.setHorizontalGroup(
            menuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuPanel3Layout.setVerticalGroup(
            menuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuTabs.addTab("Main", menuPanel3);

        menuTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu_ID:", "Item_name:", "Price:", "Category:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(menuTable4);
        if (menuTable4.getColumnModel().getColumnCount() > 0) {
            menuTable4.getColumnModel().getColumn(0).setResizable(false);
            menuTable4.getColumnModel().getColumn(1).setResizable(false);
            menuTable4.getColumnModel().getColumn(2).setResizable(false);
            menuTable4.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout menuPanel4Layout = new javax.swing.GroupLayout(menuPanel4);
        menuPanel4.setLayout(menuPanel4Layout);
        menuPanel4Layout.setHorizontalGroup(
            menuPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuPanel4Layout.setVerticalGroup(
            menuPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuTabs.addTab("Dessert", menuPanel4);

        menuTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu_ID:", "Item_name:", "Price:", "Category:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(menuTable5);
        if (menuTable5.getColumnModel().getColumnCount() > 0) {
            menuTable5.getColumnModel().getColumn(0).setResizable(false);
            menuTable5.getColumnModel().getColumn(1).setResizable(false);
            menuTable5.getColumnModel().getColumn(2).setResizable(false);
            menuTable5.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout menuPanel5Layout = new javax.swing.GroupLayout(menuPanel5);
        menuPanel5.setLayout(menuPanel5Layout);
        menuPanel5Layout.setHorizontalGroup(
            menuPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuPanel5Layout.setVerticalGroup(
            menuPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuTabs.addTab("Beverages", menuPanel5);

        displayPanel.add(menuTabs, "card2");

        editItemPanel.setBackground(new java.awt.Color(255, 255, 255));
        editItemPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        editItemPanel.setMinimumSize(new java.awt.Dimension(450, 400));
        editItemPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        editItemPanel.setSize(new java.awt.Dimension(600, 500));

        editMenuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuIDActionPerformed(evt);
            }
        });

        editPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPriceActionPerformed(evt);
            }
        });

        editMenuLabel.setText("Menu ID:");

        jLabel5.setText("Price:");

        jLabel6.setText("Item_name:");

        jLabel8.setText("Category:");

        editCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryActionPerformed(evt);
            }
        });

        editItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editItemNameActionPerformed(evt);
            }
        });

        editingTitlePanel.setBackground(new java.awt.Color(255, 255, 255));
        editingTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 78, 34), 2));

        jLabel9.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 78, 34));
        jLabel9.setText("Edit an Item");

        javax.swing.GroupLayout editingTitlePanelLayout = new javax.swing.GroupLayout(editingTitlePanel);
        editingTitlePanel.setLayout(editingTitlePanelLayout);
        editingTitlePanelLayout.setHorizontalGroup(
            editingTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editingTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        editingTitlePanelLayout.setVerticalGroup(
            editingTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editingTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(17, 17, 17))
        );

        editBtn.setText("OK");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editItemPanelLayout = new javax.swing.GroupLayout(editItemPanel);
        editItemPanel.setLayout(editItemPanelLayout);
        editItemPanelLayout.setHorizontalGroup(
            editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editItemPanelLayout.createSequentialGroup()
                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editingTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(editItemPanelLayout.createSequentialGroup()
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editItemPanelLayout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(editMenuLabel))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editItemPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editMenuID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(editItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(editItemPanelLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editItemPanelLayout.setVerticalGroup(
            editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editingTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editMenuLabel)
                    .addComponent(editMenuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editBtn)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        displayPanel.add(editItemPanel, "card3");

        showInventoryPanel.setBackground(new java.awt.Color(255, 255, 255));
        showInventoryPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        showInventoryPanel.setMinimumSize(new java.awt.Dimension(450, 400));
        showInventoryPanel.setPreferredSize(new java.awt.Dimension(600, 500));

        addingTitlePanel2.setBackground(new java.awt.Color(255, 255, 255));
        addingTitlePanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 78, 34), 2));

        jLabel20.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 78, 34));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Inventory");

        javax.swing.GroupLayout addingTitlePanel2Layout = new javax.swing.GroupLayout(addingTitlePanel2);
        addingTitlePanel2.setLayout(addingTitlePanel2Layout);
        addingTitlePanel2Layout.setHorizontalGroup(
            addingTitlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addingTitlePanel2Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        addingTitlePanel2Layout.setVerticalGroup(
            addingTitlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addingTitlePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(17, 17, 17))
        );

        showInventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "item_id", "name", "quantity", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(showInventoryTable);
        if (showInventoryTable.getColumnModel().getColumnCount() > 0) {
            showInventoryTable.getColumnModel().getColumn(0).setResizable(false);
            showInventoryTable.getColumnModel().getColumn(1).setResizable(false);
            showInventoryTable.getColumnModel().getColumn(2).setResizable(false);
            showInventoryTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout showInventoryPanelLayout = new javax.swing.GroupLayout(showInventoryPanel);
        showInventoryPanel.setLayout(showInventoryPanelLayout);
        showInventoryPanelLayout.setHorizontalGroup(
            showInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showInventoryPanelLayout.createSequentialGroup()
                .addGroup(showInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showInventoryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addingTitlePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(showInventoryPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel17)
                        .addGap(0, 360, Short.MAX_VALUE))
                    .addGroup(showInventoryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6)))
                .addContainerGap())
        );
        showInventoryPanelLayout.setVerticalGroup(
            showInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showInventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addingTitlePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        displayPanel.add(showInventoryPanel, "card4");

        rmsTitlePanel.setBackground(new java.awt.Color(94, 141, 103));
        rmsTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 78, 34), 2));

        rmsTitleLabel.setFont(new java.awt.Font("New Peninim MT", 1, 36)); // NOI18N
        rmsTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        rmsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rmsTitleLabel.setText("Restaurant Management System");

        jLabel2.setFont(new java.awt.Font("Webdings", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("æå");

        rightIcon.setFont(new java.awt.Font("Webdings", 0, 48)); // NOI18N
        rightIcon.setForeground(new java.awt.Color(255, 255, 255));
        rightIcon.setText("åæ");

        javax.swing.GroupLayout rmsTitlePanelLayout = new javax.swing.GroupLayout(rmsTitlePanel);
        rmsTitlePanel.setLayout(rmsTitlePanelLayout);
        rmsTitlePanelLayout.setHorizontalGroup(
            rmsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rmsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(rmsTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(rightIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rmsTitlePanelLayout.setVerticalGroup(
            rmsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rmsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rmsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rightIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addComponent(rmsTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rmsTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rmsTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_menu_btnActionPerformed
        // TODO add your handling code here:
        displayPanel.removeAll();
        displayPanel.repaint();
        displayPanel.revalidate();
        
        displayPanel.add(menuTabs);
        displayPanel.repaint();
        displayPanel.revalidate();
        
   
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo?", "root", "");
            Statement stmt = conn.createStatement();
            
 
            ResultSet rs=stmt.executeQuery("Select * from menulist");
            DefaultTableModel menuTableModel = (DefaultTableModel)menuTable1.getModel();
            menuTableModel.setRowCount(0);
            
            while(rs.next()){
                //data will be added until the the bottom of the table is reached
                Object table1[] = {rs.getInt("Menu_ID"),rs.getString("Item_name"), rs.getDouble("Price"), rs.getString("Category")};
                menuTableModel.addRow(table1);

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_show_menu_btnActionPerformed

    private void add_item_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_item_btnActionPerformed
        // TODO add your handling code here:
        //removing existing panels
        displayPanel.removeAll();
        displayPanel.repaint();
        displayPanel.revalidate();
        
        displayPanel.add(addItemPanel);
        displayPanel.repaint();
        displayPanel.revalidate();
        

    }//GEN-LAST:event_add_item_btnActionPerformed

    private void edit_item_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_item_btnActionPerformed
        // TODO add your handling code here:
        displayPanel.removeAll();
        displayPanel.repaint();
        displayPanel.revalidate();
        
        displayPanel.add(editItemPanel);
        displayPanel.repaint();
        displayPanel.revalidate();
       
    }//GEN-LAST:event_edit_item_btnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RestuarantManagement w=new RestuarantManagement();
        w.setVisible(true);
        w.pack();
        w.setLocation(null);
        w.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        //should close homepage on logout -figure out with maria
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void delete_item_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_item_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_item_btnActionPerformed

    private void make_order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_order_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_make_order_btnActionPerformed

    private void show_orders_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_orders_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_orders_btnActionPerformed

    private void show_inventory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_inventory_btnActionPerformed
        // TODO add your handling code here:
        //display all items in database
        displayPanel.removeAll();
        displayPanel.repaint();
        displayPanel.revalidate();
        
        displayPanel.add(showInventoryPanel);
        displayPanel.repaint();
        displayPanel.revalidate();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo?", "root", "");
            Statement stmt = conn.createStatement();
            
 
            ResultSet rs=stmt.executeQuery("Select * from inventorylist");
            DefaultTableModel menuTableModel = (DefaultTableModel)showInventoryTable.getModel();
            menuTableModel.setRowCount(0);
            
            while(rs.next()){
                //data will be added until the the bottom of the table is reached
                Object table1[] = {rs.getInt("item_id"),rs.getString("name"), rs.getInt("quantity"), rs.getDouble("price")};
                menuTableModel.addRow(table1);

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_show_inventory_btnActionPerformed

    private void addMenuID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMenuID1ActionPerformed

    private void addPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPrice1ActionPerformed

    private void addItemName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemName1ActionPerformed

    private void addItemBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtn1ActionPerformed

        Connection conn=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            PreparedStatement rs = conn.prepareStatement("Insert into menulist(Menu_ID,Item_name,Price,Category)values(?,?,?,?)");

            rs.setString(1, addMenuID1.getText());
            rs.setString(2, addItemName1.getText());
            rs.setString(3, addPrice1.getText());
            rs.setString(4, addCategory1.getText());
            
            rs.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item added");
  
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
      
        }
    }//GEN-LAST:event_addItemBtn1ActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        String menu_id = null;
        String item_name = null;
        String price = null;
        String category = null;
        DefaultTableModel tblModel = (DefaultTableModel)menuTable1.getModel();
        if (menuTable1.getSelectedRowCount() == 1){
            //if single row is selected store the values in variables
            menu_id = editMenuID.getText();
            item_name = editItemName.getText();
            price = editPrice.getText();
            category = editCategory.getText();
            
            
            //set updated value on table row
            tblModel.setValueAt(menu_id, menuTable1.getSelectedRow(), 0);
            tblModel.setValueAt(item_name, menuTable1.getSelectedRow(), 1);
            tblModel.setValueAt(price, menuTable1.getSelectedRow(), 2);
            tblModel.setValueAt(category, menuTable1.getSelectedRow(), 3);
            
            
            
        }else{
            if (menuTable1.getRowCount()== 0){
                JOptionPane.showMessageDialog(this, "Table is Empty");

            }else{
                JOptionPane.showMessageDialog(this, "Please select a single row for update...");
            }
        }
        Connection conn=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            PreparedStatement rs = conn.prepareStatement("UPDATE menulist SET Menu_ID=?,Item_name=?, Price=?, Category=? WHERE Menu_ID='"+menu_id+"'");
     
            rs.setString(1, editMenuID.getText());
            rs.setString(2, editItemName.getText());
            rs.setString(3, editPrice.getText());
            rs.setString(4, editCategory.getText());
            
            
            rs.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item updated");
  
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
      
        }
        
        
        
       
             
    }//GEN-LAST:event_editBtnActionPerformed

    private void editItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editItemNameActionPerformed

    private void editCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCategoryActionPerformed

    private void editPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPriceActionPerformed

    private void editMenuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMenuIDActionPerformed

    private void menuTabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTabsMouseClicked
        // TODO add your handling code here:
        //        int menuchoice = 1;
//        switch(menuchoice){
//            case 1:
//                menuTabsMouseClicked(menuPanel1);
//                extension = "";
//                table =menuTable1;
//                menuTabs.setSelectedIndex(0);
//                break;
//            case 2:
//                menuTabsMouseClicked(menuPanel2);
//                extension = " where Category='Appetizer'";
//                table =menuTable2;
//                menuTabs.setSelectedIndex(1);
//                break;
// 
//            case 3:
//                menuTabsMouseClicked(menuPanel3);
//                extension = " where Category='Main'";
//                table =menuTable3;
//                menuTabs.setSelectedIndex(2);
//                break;
//            case 4:
//                menuTabsMouseClicked(menuPanel4);
//                extension = " where Category='Dessert'";
//                table =menuTable4;
//                menuTabs.setSelectedIndex(3);
//                break;
//            case 5:
//                menuTabsMouseClicked(menuPanel5);
//                extension = " where Category='Beverages'";
//                table =menuTable5;
//       }
        displayPanel.removeAll();
        displayPanel.repaint();
        displayPanel.revalidate();
        
        displayPanel.add(menuTabs);
        displayPanel.repaint();
        displayPanel.revalidate();
        
        var extension = "";
        var table = menuTable1;
        if (menuTabsMouseClicked(menuPanel1)){
            extension = "";
            table =menuTable1;
//            menuTabs.setSelectedComponent(menuPanel1);
            
        }if(menuTabsMouseClicked(menuPanel2)){
            extension = " where Category='Appetizer'";
            table =menuTable2;
//            menuTabs.setSelectedComponent(menuPanel2);
            
        }if (menuTabsMouseClicked(menuPanel3)){
            extension = " where Category='Main'";
            table =menuTable3;
//            menuTabs.setSelectedComponent(menuPanel3);
            
        }if(menuTabsMouseClicked(menuPanel4)){
            extension = " where Category='Dessert'";
            table =menuTable4;
          
            
        }if(menuTabsMouseClicked(menuPanel5)){
            extension = " where Category='Beverage'";
            table =menuTable5;
          
        }
      
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo?", "root", "");
            Statement stmt = conn.createStatement();
            
            ResultSet rs=stmt.executeQuery("Select * from menulist" + extension);
            DefaultTableModel menuTableModel = (DefaultTableModel)table.getModel();
            menuTableModel.setRowCount(0);
            
            
            while(rs.next()){
                //data will be added until the the bottom of the table is reached
                Object table1[] = {rs.getInt("Menu_ID"),rs.getString("Item_name"), rs.getDouble("Price"), rs.getString("Category")};
                menuTableModel.addRow(table1);
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_menuTabsMouseClicked

    private void menuPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel3MouseClicked


    }//GEN-LAST:event_menuPanel3MouseClicked

    private void menuPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_menuPanel1MouseClicked

    private void menuPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel2MouseClicked
     
    }//GEN-LAST:event_menuPanel2MouseClicked

    private void addCategory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCategory1ActionPerformed

    private void menuTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)menuTable1.getModel();
        
        
        String Menu_id = tblmodel.getValueAt(menuTable1.getSelectedRow(), 0).toString();
        String Item_name = tblmodel.getValueAt(menuTable1.getSelectedRow(), 1).toString();
        String Price = tblmodel.getValueAt(menuTable1.getSelectedRow(), 2).toString();
        String Category = tblmodel.getValueAt(menuTable1.getSelectedRow(), 3).toString();
        
        editMenuID.setText(Menu_id);
        editItemName.setText(Item_name);
        editPrice.setText(Price);
        editCategory.setText(Category);

    }//GEN-LAST:event_menuTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addCategory1;
    private javax.swing.JButton addItemBtn1;
    private javax.swing.JTextField addItemName1;
    private javax.swing.JPanel addItemPanel;
    private javax.swing.JTextField addMenuID1;
    private javax.swing.JTextField addPrice1;
    private javax.swing.JButton add_item_btn;
    private javax.swing.JPanel addingTitlePanel1;
    private javax.swing.JPanel addingTitlePanel2;
    private javax.swing.JButton delete_item_btn;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField editCategory;
    private javax.swing.JTextField editItemName;
    private javax.swing.JPanel editItemPanel;
    private javax.swing.JTextField editMenuID;
    private javax.swing.JLabel editMenuLabel;
    private javax.swing.JTextField editPrice;
    private javax.swing.JButton edit_item_btn;
    private javax.swing.JPanel editingTitlePanel;
    private javax.swing.JPanel food_inventory_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton make_order_btn;
    private javax.swing.JPanel menuPanel1;
    private javax.swing.JPanel menuPanel2;
    private javax.swing.JPanel menuPanel3;
    private javax.swing.JPanel menuPanel4;
    private javax.swing.JPanel menuPanel5;
    private javax.swing.JTable menuTable1;
    private javax.swing.JTable menuTable2;
    private javax.swing.JTable menuTable3;
    private javax.swing.JTable menuTable4;
    private javax.swing.JTable menuTable5;
    private javax.swing.JTabbedPane menuTabs;
    private javax.swing.JLabel rightIcon;
    private javax.swing.JLabel rmsTitleLabel;
    private javax.swing.JPanel rmsTitlePanel;
    private javax.swing.JPanel showInventoryPanel;
    private javax.swing.JTable showInventoryTable;
    private javax.swing.JButton show_inventory_btn;
    private javax.swing.JButton show_menu_btn;
    private javax.swing.JButton show_orders_btn;
    // End of variables declaration//GEN-END:variables

    private Boolean menuTabsMouseClicked(JPanel menuPanel2) {
        return true;
    }
}
